/* ═══════════════════════════════════════════════════════
   EMOJI PICKER — js/emoji-picker.js
   Componente Alpine para o seletor de emoji das categorias
═══════════════════════════════════════════════════════ */

function emojiPickerData() {
  return {
    showEmojiPicker: false,
    emojiSearch: '',

    emojiList: [
      {e:'🍔',n:'hamburguer burger'},
      {e:'🍕',n:'pizza'},
      {e:'🌮',n:'taco mexicano'},
      {e:'🌯',n:'wrap burrito'},
      {e:'🍜',n:'macarrão ramen sopa'},
      {e:'🍝',n:'espaguete massa'},
      {e:'🍛',n:'curry arroz'},
      {e:'🍣',n:'sushi peixe'},
      {e:'🍱',n:'bento japonês'},
      {e:'🥗',n:'salada vegetariano'},
      {e:'🥪',n:'sanduíche lanche'},
      {e:'🍖',n:'carne osso churrasco'},
      {e:'🍗',n:'frango galinha'},
      {e:'🥩',n:'bife carne'},
      {e:'🌭',n:'cachorro quente hot dog'},
      {e:'🥓',n:'bacon'},
      {e:'🍟',n:'batata frita fritas'},
      {e:'🧀',n:'queijo'},
      {e:'🥚',n:'ovo'},
      {e:'🍳',n:'ovo frito'},
      {e:'🥞',n:'panqueca'},
      {e:'🧇',n:'waffle'},
      {e:'🥐',n:'croissant'},
      {e:'🍞',n:'pão'},
      {e:'🥖',n:'baguete'},
      {e:'🧁',n:'cupcake bolo'},
      {e:'🍰',n:'fatia bolo'},
      {e:'🎂',n:'bolo aniversário'},
      {e:'🍮',n:'pudim'},
      {e:'🍭',n:'pirulito doce'},
      {e:'🍬',n:'bala doce'},
      {e:'🍫',n:'chocolate'},
      {e:'🍩',n:'donut rosquinha'},
      {e:'🍪',n:'biscoito cookie'},
      {e:'☕',n:'café coffee'},
      {e:'🧃',n:'suco caixa'},
      {e:'🥤',n:'refrigerante copo'},
      {e:'🍵',n:'chá'},
      {e:'🧋',n:'bubble tea'},
      {e:'🍺',n:'cerveja chope'},
      {e:'🥂',n:'champanhe taça'},
      {e:'🍷',n:'vinho'},
      {e:'🍸',n:'coquetel'},
      {e:'🍹',n:'tropical drink'},
      {e:'🧊',n:'gelo'},
      {e:'🍦',n:'sorvete casquinha'},
      {e:'🍧',n:'sorvete raspado'},
      {e:'🍨',n:'sorvete pote'},
      {e:'🥟',n:'pastel gyoza'},
      {e:'🍤',n:'camarão frito tempurá'},
      {e:'🍲',n:'panela cozido'},
      {e:'🥘',n:'frigideira'},
      {e:'🫕',n:'fondue panela'},
      {e:'🥙',n:'pita wrap'},
      {e:'🧆',n:'falafel'},
      {e:'🫔',n:'burrito'},
      {e:'🥨',n:'pretzel'},
      {e:'🦞',n:'lagosta'},
      {e:'🦀',n:'siri caranguejo'},
      {e:'🐟',n:'peixe'},
      {e:'🥑',n:'abacate'},
      {e:'🍅',n:'tomate'},
      {e:'🌽',n:'milho'},
      {e:'🫑',n:'pimentão'},
      {e:'🧅',n:'cebola'},
      {e:'🧄',n:'alho'},
      {e:'🥕',n:'cenoura'},
      {e:'🥦',n:'brócolis'},
      {e:'🍄',n:'cogumelo'},
      {e:'🫒',n:'azeitona'},
      {e:'🌶️',n:'pimenta'},
      {e:'🧂',n:'sal'},
      {e:'🍯',n:'mel'},
      {e:'🧈',n:'manteiga'},
      {e:'🥜',n:'amendoim'},
      {e:'🌰',n:'castanha'},
      {e:'🍇',n:'uva'},
      {e:'🍓',n:'morango'},
      {e:'🍒',n:'cereja'},
      {e:'🍑',n:'pêssego'},
      {e:'🍍',n:'abacaxi'},
      {e:'🥭',n:'manga'},
      {e:'🍋',n:'limão'},
      {e:'🍊',n:'laranja'},
      {e:'🍎',n:'maçã'},
      {e:'🍌',n:'banana'},
      {e:'🍉',n:'melancia'},
      {e:'🫐',n:'mirtilo'},
      {e:'🥝',n:'kiwi'},
      {e:'⭐',n:'destaque especial'},
      {e:'🔥',n:'promoção quente'},
      {e:'💎',n:'premium especial'},
      {e:'🌟',n:'destaque'},
      {e:'🎯',n:'especial'},
      {e:'🏆',n:'melhor top'},
      {e:'❤️',n:'favorito'},
      {e:'🆕',n:'novo novidade'},
      {e:'📦',n:'combo kit'},
      {e:'🎁',n:'presente brinde'},
    ],

    get filteredEmojis() {
      if (!this.emojiSearch) return this.emojiList;
      const q = this.emojiSearch.toLowerCase();
      return this.emojiList.filter(em => em.n.includes(q) || em.e.includes(q));
    },

    closeEmojiPicker() {
      this.showEmojiPicker = false;
      this.emojiSearch     = '';
    },
  };
}